apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pipzwp3hw-nodejs
  janus-idp.io/tekton: pipzwp3hw-nodejs
  backstage.io/kubernetes-id: pipzwp3hw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pipzwp3hw-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
