apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pipzwp3hw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pipzwp3hw-nodejs 
  name: pipzwp3hw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pipzwp3hw-nodejs 
